### PR TITLE
Fix flaky async_payment test due to non-deterministic event ordering

### LINKED ISSUE #798: `async_payment` test is flaky
From my impression, `async_payments` starts failing more when the US wakes up and CI might be a bit slower than otherwise.

For example, see https://github.com/lightningdevkit/ldk-node/actions/runs/22224911400/job/64289081657?pr=755:

```
height 109 provided
[receiver    ] 2026-02-20 13:00:56.435 TRACE [lightning::ln::channelmanager:14891] New best block: 28b3bf3ed2948f54c19e95c01dba75f8cdcc2600b7c51f5031e3be94676cac0f at height 109
[receiver    ] 2026-02-20 13:00:56.435 TRACE [lightning::ln::channel:11737] Creating an announcement_signatures message (ch:1c0a90 p:035d11)
[receiver    ] 2026-02-20 13:00:56.435 TRACE [lightning::ln::channel:11741] Ignore: Channel is not available for public announcements (ch:1c0a90 p:035d11)
[receiver    ] 2026-02-20 13:00:56.435 INFO  [lightning::ln::channel:11497] Sending a channel_ready to our peer (ch:1c0a90 p:035d11)
[receiver    ] 2026-02-20 13:00:56.435 TRACE [lightning::ln::channelmanager:15064] Sending channel_ready with private initial channel_update for our counterparty (ch:1c0a90 p:035d11)
[receiver    ] 2026-02-20 13:00:56.435 TRACE [lightning::ln::channelmanager:5076] Attempting to generate channel update (ch:1c0a90 p:035d11)
[receiver    ] 2026-02-20 13:00:56.435 TRACE [lightning::ln::channelmanager:5083] Generating channel update (ch:1c0a90 p:035d11)
[receiver    ] 2026-02-20 13:00:56.436 DEBUG [lightning::chain::chainmonitor:1124] New best block 28b3bf3ed2948f54c19e95c01dba75f8cdcc2600b7c51f5031e3be94676cac0f at height 109 provided via block_connected
[receiver    ] 2026-02-20 13:00:56.436 TRACE [lightning::chain::channelmonitor:5545] Processing 0 matched transactions for block at height 109. (ch:1c0a90 p:035d11)
[receiver    ] 2026-02-20 13:00:56.436 TRACE [ldk_node::chain::bitcoind:412] Finished polling best tip in 37ms
[receiver    ] 2026-02-20 13:00:56.436 TRACE [lightning::ln::channelmanager:14399] Handling event ChannelReady { channel_id: 1c0a90cd1bf050ca47e38ceb36162a6953672690e8216d935a058b73b891d749, user_channel_id: 42550759974715527762479180852951833436, counterparty_node_id: PublicKey(16cf0d0705ea1e1dd8c53fdeffa9e57f8e8294a8bd84a3c58e91742b866b115d09b1a9f6909af32518d39ca6ae30c4843c07e9ac0e1d803436ee6e86ee412179), funding_txo: Some(OutPoint { txid: 48d791b8738b055a936d21e890266753692a1636eb8ce347ca50f01bcd900a1c, vout: 1 }), channel_type: [0, 16, 64] }...
[receiver    ] 2026-02-20 13:00:56.436 INFO  [ldk_node::event:1454] Channel 1c0a90cd1bf050ca47e38ceb36162a6953672690e8216d935a058b73b891d749 with counterparty 035d116b862b74918ec5a384bda894828e7fe5a9ffde3fc5d81d1eea05070dcf16 ready to be used with funding_txo 48d791b8738b055a936d21e890266753692a1636eb8ce347ca50f01bcd900a1c:1
[receiver    ] 2026-02-20 13:00:56.436 TRACE [ldk_node::chain::bitcoind:436] Finished polling mempool of size 0 and 0 evicted transactions in 0ms
[receiver    ] 2026-02-20 13:00:56.439 TRACE [lightning::ln::channelmanager:14399] Done handling event, result: Ok(())
[receiver    ] 2026-02-20 13:00:56.439 DEBUG [lightning::ln::peer_handler:2900] Handling SendChannelReady event in peer_handler for node 035d116b862b74918ec5a384bda894828e7fe5a9ffde3fc5d81d1eea05070dcf16 for channel 1c0a90cd1bf050ca47e38ceb36162a6953672690e8216d935a058b73b891d749 (ch:1c0a90 p:035d11)
[receiver    ] 2026-02-20 13:00:56.439 TRACE [lightning::ln::peer_handler:1713] Enqueueing message ChannelReady(ChannelReady { channel_id: 1c0a90cd1bf050ca47e38ceb36162a6953672690e8216d935a058b73b891d749, next_per_commitment_point: PublicKey(3d168dcd94513c2922857fc56eb25b0c63478b95f76009872955e44a042e4f708dd7bde172755e269f8a093c33bb7a34e978fdfca41945f063d0d697b729ebcc), short_channel_id_alias: Some(1099578736641) }) (p:035d11)
[receiver    ] 2026-02-20 13:00:56.439 TRACE [lightning::ln::peer_handler:3235] Handling SendChannelUpdate event in peer_handler for channel 114349209354241 (p:035d11)
[receiver    ] 2026-02-20 13:00:56.439 GOSSIP [lightning::ln::peer_handler:1711] Enqueueing message ChannelUpdate(ChannelUpdate { signature: 30440220184530afc19483e6717435ddee467bc1fb81d041cc0444dce484d49ee711b7d902205034421bffb937a57889be1953269987c83a200b63c17b5b54f88eb38f7a853f, contents: UnsignedChannelUpdate { chain_hash: 06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f, short_channel_id: 114349209354241, timestamp: 1771592456, message_flags: 3, channel_flags: 0, cltv_expiry_delta: 72, htlc_minimum_msat: 1, htlc_maximum_msat: 40000000, fee_base_msat: 1000, fee_proportional_millionths: 0, excess_data: [] } }) (p:035d11)
[receiver    ] 2026-02-20 13:00:56.440 TRACE [lightning_background_processor:1124] Persisting ChannelManager...
[receiver    ] 2026-02-20 13:00:56.440 TRACE [lightning_background_processor:1152] Done persisting ChannelManager.
[receiver    ] 2026-02-20 13:00:56.440 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:00:56.440 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for OnchainPayment: 250 sats/kwu
[receiver_lsp] 2026-02-20 13:00:56.440 TRACE [lightning::ln::peer_handler:2369] Received message ChannelReady(ChannelReady { channel_id: 1c0a90cd1bf050ca47e38ceb36162a6953672690e8216d935a058b73b891d749, next_per_commitment_point: PublicKey(3d168dcd94513c2922857fc56eb25b0c63478b95f76009872955e44a042e4f708dd7bde172755e269f8a093c33bb7a34e978fdfca41945f063d0d697b729ebcc), short_channel_id_alias: Some(1099578736641) }) (p:029c66)
[receiver_lsp] 2026-02-20 13:00:56.440 INFO  [lightning::ln::channel:7786] Received channel_ready from peer for channel 1c0a90cd1bf050ca47e38ceb36162a6953672690e8216d935a058b73b891d749 (ch:1c0a90 p:029c66)
[receiver_lsp] 2026-02-20 13:00:56.440 TRACE [lightning::ln::channel:11737] Creating an announcement_signatures message (ch:1c0a90 p:029c66)
[receiver_lsp] 2026-02-20 13:00:56.440 TRACE [lightning::ln::channel:11741] Ignore: Channel is not available for public announcements (ch:1c0a90 p:029c66)
[receiver_lsp] 2026-02-20 13:00:56.440 TRACE [lightning::ln::channelmanager:11498] Sending private initial channel_update for our counterparty (ch:1c0a90 p:029c66)
[receiver_lsp] 2026-02-20 13:00:56.440 TRACE [lightning::ln::channelmanager:5076] Attempting to generate channel update (ch:1c0a90 p:029c66)
[receiver_lsp] 2026-02-20 13:00:56.440 TRACE [lightning::ln::channelmanager:5083] Generating channel update (ch:1c0a90 p:029c66)
[receiver_lsp] 2026-02-20 13:00:56.441 GOSSIP [lightning::ln::peer_handler:2367] Received message ChannelUpdate(ChannelUpdate { signature: 30440220184530afc19483e6717435ddee467bc1fb81d041cc0444dce484d49ee711b7d902205034421bffb937a57889be1953269987c83a200b63c17b5b54f88eb38f7a853f, contents: UnsignedChannelUpdate { chain_hash: 06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f, short_channel_id: 114349209354241, timestamp: 1771592456, message_flags: 3, channel_flags: 0, cltv_expiry_delta: 72, htlc_minimum_msat: 1, htlc_maximum_msat: 40000000, fee_base_msat: 1000, fee_proportional_millionths: 0, excess_data: [] } }) (p:029c66)
[receiver_lsp] 2026-02-20 13:00:56.441 DEBUG [lightning::ln::channelmanager:12297] Received channel_update ChannelUpdate { signature: 30440220184530afc19483e6717435ddee467bc1fb81d041cc0444dce484d49ee711b7d902205034421bffb937a57889be1953269987c83a200b63c17b5b54f88eb38f7a853f, contents: UnsignedChannelUpdate { chain_hash: 06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f, short_channel_id: 114349209354241, timestamp: 1771592456, message_flags: 3, channel_flags: 0, cltv_expiry_delta: 72, htlc_minimum_msat: 1, htlc_maximum_msat: 40000000, fee_base_msat: 1000, fee_proportional_millionths: 0, excess_data: [] } }. (ch:1c0a90 p:029c66)
[receiver_lsp] 2026-02-20 13:00:56.441 DEBUG [lightning::ln::peer_handler:2015] Error handling message from 029c66f835dac1499beba7d99c7289f73689b8d22427b7eac4c87ba46d5b265782; ignoring: Ignoring channel_update with dont_forward bit set (p:029c66)
[receiver_lsp] 2026-02-20 13:00:56.441 TRACE [lightning::ln::peer_handler:3235] Handling SendChannelUpdate event in peer_handler for channel 114349209354241 (p:029c66)
[receiver_lsp] 2026-02-20 13:00:56.441 GOSSIP [lightning::ln::peer_handler:1711] Enqueueing message ChannelUpdate(ChannelUpdate { signature: 3045022100bbbe24522333fbedcf5bb536e46690cbc42704519b8ba68ca5c5f71e2decb69302205b9b38e9bf1888ace02a3a6c51c34182c934aa02da7342fddab65ab060f72f06, contents: UnsignedChannelUpdate { chain_hash: 06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f, short_channel_id: 114349209354241, timestamp: 1771592456, message_flags: 3, channel_flags: 1, cltv_expiry_delta: 72, htlc_minimum_msat: 1, htlc_maximum_msat: 360000000, fee_base_msat: 1000, fee_proportional_millionths: 0, excess_data: [] } }) (p:029c66)
[receiver_lsp] 2026-02-20 13:00:56.441 TRACE [lightning_background_processor:1124] Persisting ChannelManager...
[receiver_lsp] 2026-02-20 13:00:56.441 TRACE [lightning_background_processor:1152] Done persisting ChannelManager.
[receiver    ] 2026-02-20 13:00:56.441 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:00:56.441 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for ChannelFunding: 250 sats/kwu
[receiver    ] 2026-02-20 13:00:56.442 GOSSIP [lightning::ln::peer_handler:2367] Received message ChannelUpdate(ChannelUpdate { signature: 3045022100bbbe24522333fbedcf5bb536e46690cbc42704519b8ba68ca5c5f71e2decb69302205b9b38e9bf1888ace02a3a6c51c34182c934aa02da7342fddab65ab060f72f06, contents: UnsignedChannelUpdate { chain_hash: 06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f, short_channel_id: 114349209354241, timestamp: 1771592456, message_flags: 3, channel_flags: 1, cltv_expiry_delta: 72, htlc_minimum_msat: 1, htlc_maximum_msat: 360000000, fee_base_msat: 1000, fee_proportional_millionths: 0, excess_data: [] } }) (p:035d11)
[receiver    ] 2026-02-20 13:00:56.442 DEBUG [lightning::ln::channelmanager:12297] Received channel_update ChannelUpdate { signature: 3045022100bbbe24522333fbedcf5bb536e46690cbc42704519b8ba68ca5c5f71e2decb69302205b9b38e9bf1888ace02a3a6c51c34182c934aa02da7342fddab65ab060f72f06, contents: UnsignedChannelUpdate { chain_hash: 06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f, short_channel_id: 114349209354241, timestamp: 1771592456, message_flags: 3, channel_flags: 1, cltv_expiry_delta: 72, htlc_minimum_msat: 1, htlc_maximum_msat: 360000000, fee_base_msat: 1000, fee_proportional_millionths: 0, excess_data: [] } }. (ch:1c0a90 p:035d11)
[receiver    ] 2026-02-20 13:00:56.442 DEBUG [lightning::ln::peer_handler:2015] Error handling message from 035d116b862b74918ec5a384bda894828e7fe5a9ffde3fc5d81d1eea05070dcf16; ignoring: Ignoring channel_update with dont_forward bit set (p:035d11)
[receiver    ] 2026-02-20 13:00:56.442 TRACE [lightning_background_processor:1124] Persisting ChannelManager...
[receiver    ] 2026-02-20 13:00:56.442 TRACE [lightning_background_processor:1152] Done persisting ChannelManager.
[receiver    ] 2026-02-20 13:00:56.442 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:00:56.442 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MaximumFeeEstimate): 2775 sats/kwu
[receiver    ] 2026-02-20 13:00:56.443 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:00:56.443 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(UrgentOnChainSweep): 250 sats/kwu
[receiver    ] 2026-02-20 13:00:56.443 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MinAllowedAnchorChannelRemoteFee): 250 sats/kwu
[receiver_lsp] 2026-02-20 13:00:56.444 TRACE [lightning::ln::channelmanager:14399] Handling event ChannelReady { channel_id: 1c0a90cd1bf050ca47e38ceb36162a6953672690e8216d935a058b73b891d749, user_channel_id: 218286337941225851589783276504274696191, counterparty_node_id: PublicKey(8257265b6da47bc8c4eab72724d2b88936f789729cd9a7eb9b49c1da35f8669c8a688204235b8864ef5816054caf90e674f6062790c9ff104f8ff140b19be25b), funding_txo: Some(OutPoint { txid: 48d791b8738b055a936d21e890266753692a1636eb8ce347ca50f01bcd900a1c, vout: 1 }), channel_type: [0, 16, 64] }...
[receiver_lsp] 2026-02-20 13:00:56.444 INFO  [ldk_node::event:1454] Channel 1c0a90cd1bf050ca47e38ceb36162a6953672690e8216d935a058b73b891d749 with counterparty 029c66f835dac1499beba7d99c7289f73689b8d22427b7eac4c87ba46d5b265782 ready to be used with funding_txo 48d791b8738b055a936d21e890266753692a1636eb8ce347ca50f01bcd900a1c:1
[receiver    ] 2026-02-20 13:00:56.444 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:00:56.444 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MinAllowedNonAnchorChannelRemoteFee): 253 sats/kwu
[receiver    ] 2026-02-20 13:00:56.445 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:00:56.445 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(AnchorChannelFee): 250 sats/kwu
[receiver    ] 2026-02-20 13:00:56.445 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:00:56.445 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(NonAnchorChannelFee): 250 sats/kwu
[receiver_lsp] 2026-02-20 13:00:56.446 TRACE [lightning::ln::channelmanager:14399] Done handling event, result: Ok(())
[receiver_lsp] 2026-02-20 13:00:56.446 TRACE [lightning_background_processor:1124] Persisting ChannelManager...
[receiver_lsp] 2026-02-20 13:00:56.446 TRACE [lightning_background_processor:1152] Done persisting ChannelManager.
[receiver    ] 2026-02-20 13:00:56.446 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:00:56.446 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(ChannelCloseMinimum): 250 sats/kwu
[receiver    ] 2026-02-20 13:00:56.447 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:00:56.447 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(OutputSpendingFee): 250 sats/kwu
[sender      ] 2026-02-20 13:00:57.968 TRACE [lightning::ln::channelmanager:14859] 1 transactions included in block 28b3bf3ed2948f54c19e95c01dba75f8cdcc2600b7c51f5031e3be94676cac0f at height 109 provided
[sender      ] 2026-02-20 13:00:57.968 TRACE [lightning::ln::channelmanager:14891] New best block: 28b3bf3ed2948f54c19e95c01dba75f8cdcc2600b7c51f5031e3be94676cac0f at height 109
[sender      ] 2026-02-20 13:00:57.968 TRACE [lightning::ln::channel:11737] Creating an announcement_signatures message (ch:ead61d p:037fb9)
[sender      ] 2026-02-20 13:00:57.968 TRACE [lightning::ln::channel:11741] Ignore: Channel is not available for public announcements (ch:ead61d p:037fb9)
[sender      ] 2026-02-20 13:00:57.968 INFO  [lightning::ln::channel:11497] Sending a channel_ready to our peer (ch:ead61d p:037fb9)
[sender      ] 2026-02-20 13:00:57.968 TRACE [lightning::ln::channelmanager:15064] Sending channel_ready with private initial channel_update for our counterparty (ch:ead61d p:037fb9)
[sender      ] 2026-02-20 13:00:57.968 TRACE [lightning::ln::channelmanager:5076] Attempting to generate channel update (ch:ead61d p:037fb9)
[sender      ] 2026-02-20 13:00:57.968 TRACE [lightning::ln::channelmanager:5083] Generating channel update (ch:ead61d p:037fb9)
[sender      ] 2026-02-20 13:00:57.969 DEBUG [lightning::chain::chainmonitor:1124] New best block 28b3bf3ed2948f54c19e95c01dba75f8cdcc2600b7c51f5031e3be94676cac0f at height 109 provided via block_connected
[sender      ] 2026-02-20 13:00:57.969 TRACE [lightning::chain::channelmonitor:5545] Processing 0 matched transactions for block at height 109. (ch:ead61d p:037fb9)
[sender      ] 2026-02-20 13:00:57.969 TRACE [ldk_node::chain::bitcoind:412] Finished polling best tip in 15ms
[sender      ] 2026-02-20 13:00:57.969 TRACE [lightning_background_processor:1124] Persisting ChannelManager...
[sender      ] 2026-02-20 13:00:57.971 TRACE [lightning_background_processor:1152] Done persisting ChannelManager.
[sender      ] 2026-02-20 13:00:57.971 TRACE [ldk_node::chain::bitcoind:436] Finished polling mempool of size 0 and 0 evicted transactions in 2ms
[sender      ] 2026-02-20 13:00:57.979 TRACE [lightning::ln::channelmanager:14399] Handling event ChannelReady { channel_id: ead61d9762fdb34292a53d24394e53591af3b079ae7b65d51e74c8a25b8de538, user_channel_id: 316361353991489894028759466124095611874, counterparty_node_id: PublicKey(6571f0c91d3435cbcc133fd0628f84dcaa5bcd6d23f6bf05c4ace24db265b97fe3773580bebea37e8435dcca176fa35fe298b4e90c8881a655eb788eed0d12f5), funding_txo: Some(OutPoint { txid: 38e58d5ba2c8741ed5657bae79b0f31a59534e39243da59242b3fd62971dd6ea, vout: 0 }), channel_type: [0, 16, 64] }...
[sender      ] 2026-02-20 13:00:57.979 INFO  [ldk_node::event:1454] Channel ead61d9762fdb34292a53d24394e53591af3b079ae7b65d51e74c8a25b8de538 with counterparty 037fb965b24de2acc405bff6236dcd5baadc848f62d03f13cccb35341dc9f07165 ready to be used with funding_txo 38e58d5ba2c8741ed5657bae79b0f31a59534e39243da59242b3fd62971dd6ea:0
[sender      ] 2026-02-20 13:00:57.979 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:00:57.979 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for OnchainPayment: 250 sats/kwu
[sender      ] 2026-02-20 13:00:57.980 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:00:57.980 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for ChannelFunding: 250 sats/kwu
[sender      ] 2026-02-20 13:00:57.981 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:00:57.981 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MaximumFeeEstimate): 2775 sats/kwu
[sender      ] 2026-02-20 13:00:57.981 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:00:57.981 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(UrgentOnChainSweep): 250 sats/kwu
[sender      ] 2026-02-20 13:00:57.981 TRACE [lightning::ln::channelmanager:14399] Done handling event, result: Ok(())
[sender      ] 2026-02-20 13:00:57.981 DEBUG [lightning::ln::peer_handler:2900] Handling SendChannelReady event in peer_handler for node 037fb965b24de2acc405bff6236dcd5baadc848f62d03f13cccb35341dc9f07165 for channel ead61d9762fdb34292a53d24394e53591af3b079ae7b65d51e74c8a25b8de538 (ch:ead61d p:037fb9)
[sender      ] 2026-02-20 13:00:57.981 TRACE [lightning::ln::peer_handler:1713] Enqueueing message ChannelReady(ChannelReady { channel_id: ead61d9762fdb34292a53d24394e53591af3b079ae7b65d51e74c8a25b8de538, next_per_commitment_point: PublicKey(f66771b7ee348dc58dcba5cc971b91acd68db323b6cf588fefe4bc0dfa7eab571b1f2118f5af9e967e286c04fbe942e2993ea66a66b9068b3528b117faf4fde5), short_channel_id_alias: Some(1099630903300) }) (p:037fb9)
[sender      ] 2026-02-20 13:00:57.981 TRACE [lightning::ln::peer_handler:3235] Handling SendChannelUpdate event in peer_handler for channel 114349209419776 (p:037fb9)
[sender      ] 2026-02-20 13:00:57.981 GOSSIP [lightning::ln::peer_handler:1711] Enqueueing message ChannelUpdate(ChannelUpdate { signature: 3045022100b6bf141c0bdf13c634c98051a14e623561f71baa993773d6c28e9e4ffce76bdb022021db20b966620403108e3da3bd7f1818eb2d0942b0699e40b3f63b80d6c7ae1f, contents: UnsignedChannelUpdate { chain_hash: 06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f, short_channel_id: 114349209419776, timestamp: 1771592456, message_flags: 3, channel_flags: 0, cltv_expiry_delta: 72, htlc_minimum_msat: 1, htlc_maximum_msat: 40000000, fee_base_msat: 1000, fee_proportional_millionths: 0, excess_data: [] } }) (p:037fb9)
[sender      ] 2026-02-20 13:00:57.981 TRACE [lightning_background_processor:1124] Persisting ChannelManager...
[sender      ] 2026-02-20 13:00:57.982 TRACE [lightning_background_processor:1152] Done persisting ChannelManager.
[sender_lsp  ] 2026-02-20 13:00:57.982 TRACE [lightning::ln::peer_handler:2369] Received message ChannelReady(ChannelReady { channel_id: ead61d9762fdb34292a53d24394e53591af3b079ae7b65d51e74c8a25b8de538, next_per_commitment_point: PublicKey(f66771b7ee348dc58dcba5cc971b91acd68db323b6cf588fefe4bc0dfa7eab571b1f2118f5af9e967e286c04fbe942e2993ea66a66b9068b3528b117faf4fde5), short_channel_id_alias: Some(1099630903300) }) (p:0237e1)
[sender_lsp  ] 2026-02-20 13:00:57.982 INFO  [lightning::ln::channel:7786] Received channel_ready from peer for channel ead61d9762fdb34292a53d24394e53591af3b079ae7b65d51e74c8a25b8de538 (ch:ead61d p:0237e1)
[sender_lsp  ] 2026-02-20 13:00:57.982 TRACE [lightning::ln::channel:11737] Creating an announcement_signatures message (ch:ead61d p:0237e1)
[sender_lsp  ] 2026-02-20 13:00:57.982 TRACE [lightning::ln::channel:11741] Ignore: Channel is not available for public announcements (ch:ead61d p:0237e1)
[sender_lsp  ] 2026-02-20 13:00:57.982 TRACE [lightning::ln::channelmanager:11498] Sending private initial channel_update for our counterparty (ch:ead61d p:0237e1)
[sender_lsp  ] 2026-02-20 13:00:57.982 TRACE [lightning::ln::channelmanager:5076] Attempting to generate channel update (ch:ead61d p:0237e1)
[sender_lsp  ] 2026-02-20 13:00:57.982 TRACE [lightning::ln::channelmanager:5083] Generating channel update (ch:ead61d p:0237e1)
[sender_lsp  ] 2026-02-20 13:00:57.982 GOSSIP [lightning::ln::peer_handler:2367] Received message ChannelUpdate(ChannelUpdate { signature: 3045022100b6bf141c0bdf13c634c98051a14e623561f71baa993773d6c28e9e4ffce76bdb022021db20b966620403108e3da3bd7f1818eb2d0942b0699e40b3f63b80d6c7ae1f, contents: UnsignedChannelUpdate { chain_hash: 06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f, short_channel_id: 114349209419776, timestamp: 1771592456, message_flags: 3, channel_flags: 0, cltv_expiry_delta: 72, htlc_minimum_msat: 1, htlc_maximum_msat: 40000000, fee_base_msat: 1000, fee_proportional_millionths: 0, excess_data: [] } }) (p:0237e1)
[sender_lsp  ] 2026-02-20 13:00:57.983 DEBUG [lightning::ln::channelmanager:12297] Received channel_update ChannelUpdate { signature: 3045022100b6bf141c0bdf13c634c98051a14e623561f71baa993773d6c28e9e4ffce76bdb022021db20b966620403108e3da3bd7f1818eb2d0942b0699e40b3f63b80d6c7ae1f, contents: UnsignedChannelUpdate { chain_hash: 06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f, short_channel_id: 114349209419776, timestamp: 1771592456, message_flags: 3, channel_flags: 0, cltv_expiry_delta: 72, htlc_minimum_msat: 1, htlc_maximum_msat: 40000000, fee_base_msat: 1000, fee_proportional_millionths: 0, excess_data: [] } }. (ch:ead61d p:0237e1)
[sender_lsp  ] 2026-02-20 13:00:57.983 DEBUG [lightning::ln::peer_handler:2015] Error handling message from 0237e125d4ccf004620a01d0595c2c27011d11e51d702d8933488825041dc29a4c; ignoring: Ignoring channel_update with dont_forward bit set (p:0237e1)
[sender_lsp  ] 2026-02-20 13:00:57.983 TRACE [lightning::ln::peer_handler:3235] Handling SendChannelUpdate event in peer_handler for channel 114349209419776 (p:0237e1)
[sender_lsp  ] 2026-02-20 13:00:57.983 GOSSIP [lightning::ln::peer_handler:1711] Enqueueing message ChannelUpdate(ChannelUpdate { signature: 3044022042ed491cd2762e158b91035a29a19b4d7ad7a33914ce6e2153965a9b031ed22e02207baa3eba1066ed63ef22e0d6b9f415246b1b0589fa92a117066845bc3513e328, contents: UnsignedChannelUpdate { chain_hash: 06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f, short_channel_id: 114349209419776, timestamp: 1771592456, message_flags: 3, channel_flags: 1, cltv_expiry_delta: 72, htlc_minimum_msat: 1, htlc_maximum_msat: 360000000, fee_base_msat: 1000, fee_proportional_millionths: 0, excess_data: [] } }) (p:0237e1)
[sender      ] 2026-02-20 13:00:57.983 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MinAllowedAnchorChannelRemoteFee): 250 sats/kwu
[sender_lsp  ] 2026-02-20 13:00:57.983 TRACE [lightning_background_processor:1124] Persisting ChannelManager...
[sender_lsp  ] 2026-02-20 13:00:57.984 TRACE [lightning_background_processor:1152] Done persisting ChannelManager.
[sender      ] 2026-02-20 13:00:57.984 GOSSIP [lightning::ln::peer_handler:2367] Received message ChannelUpdate(ChannelUpdate { signature: 3044022042ed491cd2762e158b91035a29a19b4d7ad7a33914ce6e2153965a9b031ed22e02207baa3eba1066ed63ef22e0d6b9f415246b1b0589fa92a117066845bc3513e328, contents: UnsignedChannelUpdate { chain_hash: 06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f, short_channel_id: 114349209419776, timestamp: 1771592456, message_flags: 3, channel_flags: 1, cltv_expiry_delta: 72, htlc_minimum_msat: 1, htlc_maximum_msat: 360000000, fee_base_msat: 1000, fee_proportional_millionths: 0, excess_data: [] } }) (p:037fb9)
[sender      ] 2026-02-20 13:00:57.984 DEBUG [lightning::ln::channelmanager:12297] Received channel_update ChannelUpdate { signature: 3044022042ed491cd2762e158b91035a29a19b4d7ad7a33914ce6e2153965a9b031ed22e02207baa3eba1066ed63ef22e0d6b9f415246b1b0589fa92a117066845bc3513e328, contents: UnsignedChannelUpdate { chain_hash: 06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f, short_channel_id: 114349209419776, timestamp: 1771592456, message_flags: 3, channel_flags: 1, cltv_expiry_delta: 72, htlc_minimum_msat: 1, htlc_maximum_msat: 360000000, fee_base_msat: 1000, fee_proportional_millionths: 0, excess_data: [] } }. (ch:ead61d p:037fb9)
[sender      ] 2026-02-20 13:00:57.984 DEBUG [lightning::ln::peer_handler:2015] Error handling message from 037fb965b24de2acc405bff6236dcd5baadc848f62d03f13cccb35341dc9f07165; ignoring: Ignoring channel_update with dont_forward bit set (p:037fb9)
[sender      ] 2026-02-20 13:00:57.984 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:00:57.984 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MinAllowedNonAnchorChannelRemoteFee): 253 sats/kwu
[sender      ] 2026-02-20 13:00:57.984 TRACE [lightning_background_processor:1124] Persisting ChannelManager...
[sender      ] 2026-02-20 13:00:57.985 TRACE [lightning_background_processor:1152] Done persisting ChannelManager.
[sender      ] 2026-02-20 13:00:57.985 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:00:57.985 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(AnchorChannelFee): 250 sats/kwu
[sender      ] 2026-02-20 13:00:57.985 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:00:57.985 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(NonAnchorChannelFee): 250 sats/kwu
[sender      ] 2026-02-20 13:00:57.986 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:00:57.986 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(ChannelCloseMinimum): 250 sats/kwu
[sender_lsp  ] 2026-02-20 13:00:57.986 TRACE [lightning::ln::channelmanager:14399] Handling event ChannelReady { channel_id: ead61d9762fdb34292a53d24394e53591af3b079ae7b65d51e74c8a25b8de538, user_channel_id: 139125026652381308934210529807692036690, counterparty_node_id: PublicKey(4c9ac21d0425884833892d701de5111d01272c5c59d0010a6204f0ccd425e137bc9ce103edf9b792787c5a556e99d421bf8f8959408123b8cc788830b43596a4), funding_txo: Some(OutPoint { txid: 38e58d5ba2c8741ed5657bae79b0f31a59534e39243da59242b3fd62971dd6ea, vout: 0 }), channel_type: [0, 16, 64] }...
[sender_lsp  ] 2026-02-20 13:00:57.986 INFO  [ldk_node::event:1454] Channel ead61d9762fdb34292a53d24394e53591af3b079ae7b65d51e74c8a25b8de538 with counterparty 0237e125d4ccf004620a01d0595c2c27011d11e51d702d8933488825041dc29a4c ready to be used with funding_txo 38e58d5ba2c8741ed5657bae79b0f31a59534e39243da59242b3fd62971dd6ea:0
[sender      ] 2026-02-20 13:00:57.987 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:00:57.987 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(OutputSpendingFee): 250 sats/kwu
[sender_lsp  ] 2026-02-20 13:00:57.989 TRACE [lightning::ln::channelmanager:14399] Done handling event, result: Ok(())
[sender_lsp  ] 2026-02-20 13:00:57.989 TRACE [lightning_background_processor:1124] Persisting ChannelManager...
[sender_lsp  ] 2026-02-20 13:00:57.990 TRACE [lightning_background_processor:1152] Done persisting ChannelManager.
[sender_lsp  ] 2026-02-20 13:00:58.140 TRACE [ldk_node::chain::bitcoind:436] Finished polling mempool of size 0 and 0 evicted transactions in 0ms
[receiver_lsp] 2026-02-20 13:00:58.282 TRACE [ldk_node::chain::bitcoind:436] Finished polling mempool of size 0 and 0 evicted transactions in 0ms
[receiver    ] 2026-02-20 13:00:58.398 TRACE [ldk_node::chain::bitcoind:436] Finished polling mempool of size 0 and 0 evicted transactions in 0ms
[sender      ] 2026-02-20 13:00:59.961 TRACE [ldk_node::chain::bitcoind:436] Finished polling mempool of size 0 and 0 evicted transactions in 1ms
[sender_lsp  ] 2026-02-20 13:01:00.129 TRACE [ldk_node::chain::bitcoind:436] Finished polling mempool of size 0 and 0 evicted transactions in 0ms
[receiver_lsp] 2026-02-20 13:01:00.282 TRACE [ldk_node::chain::bitcoind:436] Finished polling mempool of size 0 and 0 evicted transactions in 1ms
[receiver    ] 2026-02-20 13:01:00.401 TRACE [ldk_node::chain::bitcoind:436] Finished polling mempool of size 0 and 0 evicted transactions in 1ms
[sender      ] 2026-02-20 13:01:00.608 TRACE [lightning_background_processor:1325] Calling OnionMessageHandler's timer_tick_occurred
[sender_lsp  ] 2026-02-20 13:01:00.711 TRACE [lightning_background_processor:1325] Calling OnionMessageHandler's timer_tick_occurred
[receiver_lsp] 2026-02-20 13:01:00.772 TRACE [lightning_background_processor:1325] Calling OnionMessageHandler's timer_tick_occurred
[receiver    ] 2026-02-20 13:01:00.875 TRACE [lightning_background_processor:1325] Calling OnionMessageHandler's timer_tick_occurred
 Done!

[sender      ] 2026-02-20 13:01:01.048 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:01:01.048 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for OnchainPayment: 250 sats/kwu
[sender      ] 2026-02-20 13:01:01.048 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:01:01.048 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for ChannelFunding: 250 sats/kwu
[sender      ] 2026-02-20 13:01:01.049 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:01:01.049 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MaximumFeeEstimate): 2775 sats/kwu
[sender      ] 2026-02-20 13:01:01.049 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:01:01.049 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(UrgentOnChainSweep): 250 sats/kwu
[sender      ] 2026-02-20 13:01:01.050 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MinAllowedAnchorChannelRemoteFee): 250 sats/kwu
[sender      ] 2026-02-20 13:01:01.050 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:01:01.050 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MinAllowedNonAnchorChannelRemoteFee): 253 sats/kwu
[sender      ] 2026-02-20 13:01:01.051 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:01:01.051 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(AnchorChannelFee): 250 sats/kwu
[sender      ] 2026-02-20 13:01:01.051 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:01:01.051 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(NonAnchorChannelFee): 250 sats/kwu
[sender      ] 2026-02-20 13:01:01.052 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:01:01.052 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(ChannelCloseMinimum): 250 sats/kwu
[sender      ] 2026-02-20 13:01:01.052 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender      ] 2026-02-20 13:01:01.052 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(OutputSpendingFee): 250 sats/kwu
[sender      ] 2026-02-20 13:01:01.059 TRACE [ldk_node::chain::bitcoind:436] Finished polling mempool of size 0 and 0 evicted transactions in 0ms
[sender_lsp  ] 2026-02-20 13:01:01.066 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender_lsp  ] 2026-02-20 13:01:01.066 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for OnchainPayment: 250 sats/kwu
[sender_lsp  ] 2026-02-20 13:01:01.066 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender_lsp  ] 2026-02-20 13:01:01.066 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for ChannelFunding: 250 sats/kwu
[sender_lsp  ] 2026-02-20 13:01:01.067 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender_lsp  ] 2026-02-20 13:01:01.067 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MaximumFeeEstimate): 2775 sats/kwu
[sender_lsp  ] 2026-02-20 13:01:01.067 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender_lsp  ] 2026-02-20 13:01:01.067 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(UrgentOnChainSweep): 250 sats/kwu
[sender_lsp  ] 2026-02-20 13:01:01.067 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MinAllowedAnchorChannelRemoteFee): 250 sats/kwu
[sender_lsp  ] 2026-02-20 13:01:01.068 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender_lsp  ] 2026-02-20 13:01:01.068 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MinAllowedNonAnchorChannelRemoteFee): 253 sats/kwu
[sender_lsp  ] 2026-02-20 13:01:01.068 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender_lsp  ] 2026-02-20 13:01:01.068 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(AnchorChannelFee): 250 sats/kwu
[sender_lsp  ] 2026-02-20 13:01:01.069 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender_lsp  ] 2026-02-20 13:01:01.069 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(NonAnchorChannelFee): 250 sats/kwu
[sender_lsp  ] 2026-02-20 13:01:01.069 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender_lsp  ] 2026-02-20 13:01:01.069 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(ChannelCloseMinimum): 250 sats/kwu
[sender_lsp  ] 2026-02-20 13:01:01.070 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[sender_lsp  ] 2026-02-20 13:01:01.070 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(OutputSpendingFee): 250 sats/kwu
[sender_lsp  ] 2026-02-20 13:01:01.073 TRACE [ldk_node::chain::bitcoind:436] Finished polling mempool of size 0 and 0 evicted transactions in 0ms
[receiver_lsp] 2026-02-20 13:01:01.077 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver_lsp] 2026-02-20 13:01:01.077 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for OnchainPayment: 250 sats/kwu
[receiver_lsp] 2026-02-20 13:01:01.078 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver_lsp] 2026-02-20 13:01:01.078 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for ChannelFunding: 250 sats/kwu
[receiver_lsp] 2026-02-20 13:01:01.078 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver_lsp] 2026-02-20 13:01:01.078 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MaximumFeeEstimate): 2775 sats/kwu
[receiver_lsp] 2026-02-20 13:01:01.079 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver_lsp] 2026-02-20 13:01:01.079 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(UrgentOnChainSweep): 250 sats/kwu
[receiver_lsp] 2026-02-20 13:01:01.079 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MinAllowedAnchorChannelRemoteFee): 250 sats/kwu
[receiver_lsp] 2026-02-20 13:01:01.080 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver_lsp] 2026-02-20 13:01:01.080 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MinAllowedNonAnchorChannelRemoteFee): 253 sats/kwu
[receiver_lsp] 2026-02-20 13:01:01.080 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver_lsp] 2026-02-20 13:01:01.080 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(AnchorChannelFee): 250 sats/kwu
[receiver_lsp] 2026-02-20 13:01:01.081 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver_lsp] 2026-02-20 13:01:01.081 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(NonAnchorChannelFee): 250 sats/kwu
[receiver_lsp] 2026-02-20 13:01:01.081 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver_lsp] 2026-02-20 13:01:01.081 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(ChannelCloseMinimum): 250 sats/kwu
[receiver_lsp] 2026-02-20 13:01:01.082 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver_lsp] 2026-02-20 13:01:01.082 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(OutputSpendingFee): 250 sats/kwu
[receiver_lsp] 2026-02-20 13:01:01.085 TRACE [ldk_node::chain::bitcoind:436] Finished polling mempool of size 0 and 0 evicted transactions in 0ms
[receiver    ] 2026-02-20 13:01:01.090 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:01:01.090 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for OnchainPayment: 250 sats/kwu
[receiver    ] 2026-02-20 13:01:01.090 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:01:01.090 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for ChannelFunding: 250 sats/kwu
[receiver    ] 2026-02-20 13:01:01.091 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:01:01.091 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MaximumFeeEstimate): 2775 sats/kwu
[receiver    ] 2026-02-20 13:01:01.091 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:01:01.091 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(UrgentOnChainSweep): 250 sats/kwu
[receiver    ] 2026-02-20 13:01:01.092 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MinAllowedAnchorChannelRemoteFee): 250 sats/kwu
[receiver    ] 2026-02-20 13:01:01.092 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:01:01.092 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(MinAllowedNonAnchorChannelRemoteFee): 253 sats/kwu
[receiver    ] 2026-02-20 13:01:01.093 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:01:01.093 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(AnchorChannelFee): 250 sats/kwu
[receiver    ] 2026-02-20 13:01:01.093 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:01:01.093 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(NonAnchorChannelFee): 250 sats/kwu
[receiver    ] 2026-02-20 13:01:01.094 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:01:01.094 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(ChannelCloseMinimum): 250 sats/kwu
[receiver    ] 2026-02-20 13:01:01.094 ERROR [ldk_node::chain::bitcoind:527] Failed to retrieve fee rate estimates: ["Insufficient data or no feerate found"]. Falling back to default of 1 sat/vb.
[receiver    ] 2026-02-20 13:01:01.094 TRACE [ldk_node::chain::bitcoind:552] Fee rate estimation updated for Lightning(OutputSpendingFee): 250 sats/kwu
[receiver    ] 2026-02-20 13:01:01.097 TRACE [ldk_node::chain::bitcoind:436] Finished polling mempool of size 0 and 0 evicted transactions in 0ms
0237e125d4ccf004620a01d0595c2c27011d11e51d702d8933488825041dc29a4c got event ChannelReady { channel_id: ead61d9762fdb34292a53d24394e53591af3b079ae7b65d51e74c8a25b8de538, user_channel_id: UserChannelId(316361353991489894028759466124095611874), counterparty_node_id: Some(PublicKey(6571f0c91d3435cbcc133fd0628f84dcaa5bcd6d23f6bf05c4ace24db265b97fe3773580bebea37e8435dcca176fa35fe298b4e90c8881a655eb788eed0d12f5)), funding_txo: Some(OutPoint { txid: 38e58d5ba2c8741ed5657bae79b0f31a59534e39243da59242b3fd62971dd6ea, vout: 0 }) }
037fb965b24de2acc405bff6236dcd5baadc848f62d03f13cccb35341dc9f07165 got event ChannelReady { channel_id: f4c5c1b80596b912f073b09051803d290eadcd70e29a4e5204357f8d45c1a661, user_channel_id: UserChannelId(230419362063788922601601626540339491062), counterparty_node_id: Some(PublicKey(16cf0d0705ea1e1dd8c53fdeffa9e57f8e8294a8bd84a3c58e91742b866b115d09b1a9f6909af32518d39ca6ae30c4843c07e9ac0e1d803436ee6e86ee412179)), funding_txo: Some(OutPoint { txid: 60a6c1458d7f3504524e9ae270cdad0e293d805190b073f012b99605b8c1c5f4, vout: 1 }) }

thread 'async_payment' panicked at tests/integration_tests_rust.rs:1346:5:
assertion `left == right` failed
  left: Some(PublicKey(16cf0d0705ea1e1dd8c53fdeffa9e57f8e8294a8bd84a3c58e91742b866b115d09b1a9f6909af32518d39ca6ae30c4843c07e9ac0e1d803436ee6e86ee412179))
 right: Some(PublicKey(4c9ac21d0425884833892d701de5111d01272c5c59d0010a6204f0ccd425e137bc9ce103edf9b792787c5a556e99d421bf8f8959408123b8cc788830b43596a4))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[receiver    ] 2026-02-20 13:01:01.104 INFO  [ldk_node:678] Shutting down LDK Node with node ID 029c66f835dac1499beba7d99c7289f73689b8d22427b7eac4c87ba46d5b265782...
[receiver    ] 2026-02-20 13:01:01.104 TRACE [ldk_node:684] Sent shutdown signal to background tasks.
[receiver    ] 2026-02-20 13:01:01.104 TRACE [ldk_node::chain::bitcoind:284] Stopping polling for new chain data.
[receiver    ] 2026-02-20 13:01:01.104 TRACE [lightning::ln::peer_handler:3444] Disconnecting peer due to client request to disconnect all peers (p:035d11)
[receiver    ] 2026-02-20 13:01:01.104 DEBUG [lightning::ln::channelmanager:14429] Marking channels disconnected and generating channel_updates. (p:035d11)
[receiver    ] 2026-02-20 13:01:01.104 TRACE [lightning::ln::channel:9336] Peer disconnection resulted in 0 remote-announced HTLC drops on channel 1c0a90cd1bf050ca47e38ceb36162a6953672690e8216d935a058b73b891d749 (ch:1c0a90 p:035d11)
[receiver    ] 2026-02-20 13:01:01.104 DEBUG [ldk_node:700] Disconnected all network peers.
[receiver    ] 2026-02-20 13:01:01.104 TRACE [ldk_node::runtime:141] Stopped background task with id 142
[receiver    ] 2026-02-20 13:01:01.104 DEBUG [ldk_node::runtime:149] Stopped all background tasks
[receiver    ] 2026-02-20 13:01:01.104 DEBUG [ldk_node:707] Stopped chain sources.
[receiver    ] 2026-02-20 13:01:01.104 TRACE [ldk_node:713] Sent shutdown signal to background processor.
[receiver    ] 2026-02-20 13:01:01.104 DEBUG [ldk_node:607] Stopping processing events.
[receiver    ] 2026-02-20 13:01:01.104 TRACE [lightning_background_processor:1371] Terminating background processor.
[receiver_lsp] 2026-02-20 13:01:01.105 TRACE [lightning::ln::peer_handler:3471] Handling disconnection of peer because the socket was disconnected (p:029c66)
[receiver_lsp] 2026-02-20 13:01:01.105 DEBUG [lightning::ln::channelmanager:14429] Marking channels disconnected and generating channel_updates. (p:029c66)
[receiver_lsp] 2026-02-20 13:01:01.105 TRACE [lightning::ln::channel:9336] Peer disconnection resulted in 0 remote-announced HTLC drops on channel 1c0a90cd1bf050ca47e38ceb36162a6953672690e8216d935a058b73b891d749 (ch:1c0a90 p:029c66)
[receiver    ] 2026-02-20 13:01:01.110 DEBUG [ldk_node::runtime:180] Stopped background processing of events.
[receiver    ] 2026-02-20 13:01:01.110 INFO  [ldk_node:730] Shutdown complete.
[receiver_lsp] 2026-02-20 13:01:01.111 INFO  [ldk_node:678] Shutting down LDK Node with node ID 035d116b862b74918ec5a384bda894828e7fe5a9ffde3fc5d81d1eea05070dcf16...
[receiver_lsp] 2026-02-20 13:01:01.111 TRACE [ldk_node:684] Sent shutdown signal to background tasks.
[receiver_lsp] 2026-02-20 13:01:01.111 TRACE [ldk_node::chain::bitcoind:284] Stopping polling for new chain data.
[receiver_lsp] 2026-02-20 13:01:01.111 TRACE [lightning::ln::peer_handler:3444] Disconnecting peer due to client request to disconnect all peers (p:037fb9)
[receiver_lsp] 2026-02-20 13:01:01.111 DEBUG [lightning::ln::channelmanager:14429] Marking channels disconnected and generating channel_updates. (p:037fb9)
[receiver_lsp] 2026-02-20 13:01:01.111 TRACE [lightning::ln::channel:9336] Peer disconnection resulted in 0 remote-announced HTLC drops on channel f4c5c1b80596b912f073b09051803d290eadcd70e29a4e5204357f8d45c1a661 (ch:f4c5c1 p:037fb9)
[receiver_lsp] 2026-02-20 13:01:01.111 DEBUG [ldk_node:700] Disconnected all network peers.
[receiver_lsp] 2026-02-20 13:01:01.111 TRACE [ldk_node::runtime:141] Stopped background task with id 124
[receiver_lsp] 2026-02-20 13:01:01.111 DEBUG [ldk_node::runtime:149] Stopped all background tasks
[receiver_lsp] 2026-02-20 13:01:01.111 DEBUG [ldk_node:707] Stopped chain sources.
[receiver_lsp] 2026-02-20 13:01:01.111 TRACE [ldk_node:713] Sent shutdown signal to background processor.
[receiver_lsp] 2026-02-20 13:01:01.111 DEBUG [ldk_node:607] Stopping processing events.
[receiver_lsp] 2026-02-20 13:01:01.111 TRACE [lightning_background_processor:1371] Terminating background processor.
[sender_lsp  ] 2026-02-20 13:01:01.112 TRACE [lightning::ln::peer_handler:3471] Handling disconnection of peer because the socket was disconnected (p:035d11)
[sender_lsp  ] 2026-02-20 13:01:01.112 DEBUG [lightning::ln::channelmanager:14429] Marking channels disconnected and generating channel_updates. (p:035d11)
[sender_lsp  ] 2026-02-20 13:01:01.112 TRACE [lightning::ln::channel:9336] Peer disconnection resulted in 0 remote-announced HTLC drops on channel f4c5c1b80596b912f073b09051803d290eadcd70e29a4e5204357f8d45c1a661 (ch:f4c5c1 p:035d11)
[receiver_lsp] 2026-02-20 13:01:01.119 DEBUG [ldk_node::runtime:180] Stopped background processing of events.
[receiver_lsp] 2026-02-20 13:01:01.119 INFO  [ldk_node:730] Shutdown complete.
[sender_lsp  ] 2026-02-20 13:01:01.119 INFO  [ldk_node:678] Shutting down LDK Node with node ID 037fb965b24de2acc405bff6236dcd5baadc848f62d03f13cccb35341dc9f07165...
[sender_lsp  ] 2026-02-20 13:01:01.119 TRACE [ldk_node:684] Sent shutdown signal to background tasks.
[sender_lsp  ] 2026-02-20 13:01:01.119 TRACE [ldk_node::chain::bitcoind:284] Stopping polling for new chain data.
[sender_lsp  ] 2026-02-20 13:01:01.119 TRACE [lightning::ln::peer_handler:3444] Disconnecting peer due to client request to disconnect all peers (p:0237e1)
[sender_lsp  ] 2026-02-20 13:01:01.119 DEBUG [lightning::ln::channelmanager:14429] Marking channels disconnected and generating channel_updates. (p:0237e1)
[sender_lsp  ] 2026-02-20 13:01:01.119 TRACE [lightning::ln::channel:9336] Peer disconnection resulted in 0 remote-announced HTLC drops on channel ead61d9762fdb34292a53d24394e53591af3b079ae7b65d51e74c8a25b8de538 (ch:ead61d p:0237e1)
[sender_lsp  ] 2026-02-20 13:01:01.119 DEBUG [ldk_node:700] Disconnected all network peers.
[sender_lsp  ] 2026-02-20 13:01:01.119 TRACE [ldk_node::runtime:141] Stopped background task with id 106
[sender_lsp  ] 2026-02-20 13:01:01.119 DEBUG [ldk_node::runtime:149] Stopped all background tasks
[sender_lsp  ] 2026-02-20 13:01:01.119 DEBUG [ldk_node:707] Stopped chain sources.
[sender_lsp  ] 2026-02-20 13:01:01.119 TRACE [ldk_node:713] Sent shutdown signal to background processor.
[sender_lsp  ] 2026-02-20 13:01:01.119 DEBUG [ldk_node:607] Stopping processing events.
[sender_lsp  ] 2026-02-20 13:01:01.119 TRACE [lightning_background_processor:1371] Terminating background processor.
[sender      ] 2026-02-20 13:01:01.120 TRACE [lightning::ln::peer_handler:3471] Handling disconnection of peer because the socket was disconnected (p:037fb9)
[sender      ] 2026-02-20 13:01:01.120 DEBUG [lightning::ln::channelmanager:14429] Marking channels disconnected and generating channel_updates. (p:037fb9)
[sender      ] 2026-02-20 13:01:01.120 TRACE [lightning::ln::channel:9336] Peer disconnection resulted in 0 remote-announced HTLC drops on channel ead61d9762fdb34292a53d24394e53591af3b079ae7b65d51e74c8a25b8de538 (ch:ead61d p:037fb9)
[sender_lsp  ] 2026-02-20 13:01:01.126 DEBUG [ldk_node::runtime:180] Stopped background processing of events.
[sender_lsp  ] 2026-02-20 13:01:01.126 INFO  [ldk_node:730] Shutdown complete.
[sender      ] 2026-02-20 13:01:01.126 INFO  [ldk_node:678] Shutting down LDK Node with node ID 0237e125d4ccf004620a01d0595c2c27011d11e51d702d8933488825041dc29a4c...
[sender      ] 2026-02-20 13:01:01.126 TRACE [ldk_node:684] Sent shutdown signal to background tasks.
[sender      ] 2026-02-20 13:01:01.127 TRACE [ldk_node::chain::bitcoind:284] Stopping polling for new chain data.
[sender      ] 2026-02-20 13:01:01.127 DEBUG [ldk_node:700] Disconnected all network peers.
[sender      ] 2026-02-20 13:01:01.127 TRACE [ldk_node::runtime:141] Stopped background task with id 65
[sender      ] 2026-02-20 13:01:01.127 DEBUG [ldk_node::runtime:149] Stopped all background tasks
[sender      ] 2026-02-20 13:01:01.127 DEBUG [ldk_node:707] Stopped chain sources.
[sender      ] 2026-02-20 13:01:01.127 TRACE [ldk_node:713] Sent shutdown signal to background processor.
[sender      ] 2026-02-20 13:01:01.127 DEBUG [ldk_node:607] Stopping processing events.
[sender      ] 2026-02-20 13:01:01.127 TRACE [lightning_background_processor:1371] Terminating background processor.
[sender      ] 2026-02-20 13:01:01.134 DEBUG [ldk_node::runtime:180] Stopped background processing of events.
[sender      ] 2026-02-20 13:01:01.134 INFO  [ldk_node:730] Shutdown complete.


failures:
    async_payment

test result: FAILED. 31 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 349.84s
```

### PR DESCRIPTION
**Pull request by joostjager**
node_sender_lsp and node_receiver_lsp each have two channels, so they receive two ChannelReady events whose order depends on timing. The test previously consumed these events in a fixed order, which could fail when the events arrive in the opposite order.

Reproduced locally by swapping the assertion order at line 1346-1347, which fails deterministically since the "normal" local ordering is the opposite of the one expected by the swapped assertions.

Add an expect_channel_ready_events\! macro that consumes two ChannelReady events and asserts both expected counterparties are present regardless of arrival order.

Fixes #798

### CODE REVIEW

File: tests/common/mod.rs [hunk 1]
```diff
@@ -98,6 +98,34 @@ macro_rules! expect_channel_ready_event {
 
 pub(crate) use expect_channel_ready_event;
 
+macro_rules! expect_channel_ready_events {
```
Comment (tnull) [inline tests/common/mod.rs:101]: nit: Could have named it `expect_two_channel_ready_events`.

Comment (joostjager) [reply tests/common/mod.rs:101]: yes, would've been better
